// Copyright 2015
// Ubiquitous Knowledge Processing (UKP) Lab and FG Language Technology
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_troubleshooting]]
== Troubleshooting

We are collecting error reports to improve the tool. For this, the error must be reproducible: 
If you find a way how to produce the error, please open an issue and describe it.

=== Session timeout

If the tool is kept open in the browser, but not used for a long period of time, you will have to log in again. For this, press the reload button of your browser.

=== Forgot admin password

If you locked yourself out of the WebAnno, you can reset/recreated the default admin account. In order to do so, first stop WebAnno if it is still running. Then specify the system property `webanno.restoreDefaultAdminAccount` when you start WebAnno (note that the value of the property does not matter!). For example, if you are using the standalone version of WebAnno, you can start it as 

[source,bash,subs="+attributes"]
----
$ java -Dwebanno.restoreDefaultAdminAccount -jar webanno-standalone-{revnumber}.jar
----

NOTE: Mind that if you are using a non-default `webanno.home`, you also have to specify this system property.

When WebAnno has started, try opening it in your browser. The login page will show, but it will not allow you to log in. Instead a message will be shown stating that the default admin account has been reset or recreated. In order to resume normal operations, stop WebAnno again and restart it without the `webanno.restoreDefaultAdminAccount` system property.
